name: TicketWatcher

on:
  issues:
    types: [opened, reopened, labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true   # ok if empty/absent
          pip install -e .                          # <-- installs src/ticketwatcher

      - name: Run TicketWatcher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional: target PR base branch
          TICKETWATCHER_BASE_BRANCH: r_dev
        run: |
          python -m ticketwatcher --event-file "$GITHUB_EVENT_PATH"
